version: "3.9"

services:
    php:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        depends_on:
            - mysql
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    ### Nginx Server Container ##################################

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - php
        restart: unless-stopped
        tty: true
        ports:
            - "1010:80"
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            TZ: Asia/Bangkok
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/conf.d/demo.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/log:/var/log/nginx
        networks:
            - app-network

    mysql:
        image: mysql/mysql-server:latest
        tty: true
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'test_db'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'test_pass'
            MYSQL_ROOT_HOST: '%' # needs to be enclosed with quotes
            TZ: 'Asia/Bangkok'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        networks:
            - app-network


# Docker Networks
networks:
    app-network:
        driver: bridge

# Volumes
volumes:
    mysqldata:
        driver: local
